config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  root 'pages#home'
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  resources :posts do
  collection do
    get 'hobby'
    get 'study'
    get 'team'
  end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  default_scope -> { includes(:user).order(created_at: :desc) }
  
  scope :by_category, -> (branch, category_name) do
    joins(:category).where(categories: {name: category_name, branch: branch})
  end

  scope :by_branch, -> (branch) do
    joins(:category).where(categories: {branch: branch})
  end

  scope :search, -> (search) do
    where("title ILIKE lower(?) OR content ILIKE lower(?)", "%#{search}%", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  def after_sign_out_path_for(resource_or_scope)
    root_path 
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
  end
  
  def hobby
    posts_for_branch(params[:action])
  end

  def study
    posts_for_branch(params[:action])
  end

  def team
    posts_for_branch(params[:action])
  end

private

  def get_posts
    branch = params[:action]
    search = params[:search]
    category = params[:category]

    if category.blank? && search.blank?
      posts = Post.by_branch(branch).all
    elsif category.blank? && search.present?
      posts = Post.by_branch(branch).search(search)
    elsif category.present? && search.blank?
      posts = Post.by_category(branch, category)
    elsif category.present? && search.present?
      posts = Post.by_category(branch, category).search(search)
    end
  end

  def posts_for_branch(branch)
    @categories = Category.where(branch: branch)
    @posts = get_posts.paginate(page: params[:page])
    respond_to do |format|
      format.html
      format.js { render partial: 'posts/posts_pagination_page' }
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def after_sign_up_path_for(resource_or_scope)
    root_path
  end



  def sign_up_params
    params.require(:user).permit( :name, 
                                  :email, 
                                  :password, 
                                  :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit( :name, 
                                  :email, 
                                  :password, 
                                  :password_confirmation, 
                                  :current_password)
  end
end

app/helpers/application_helper.rb
require 'navigation_helper.rb'

module ApplicationHelper
  include NavigationHelper
  include PostsHelper

  def flash_class(level)
    case level
    when :notice then "info"
    when :error then "error"
    when :alert then "warning"
    end
  end
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def create_new_post_partial_path
      if user_signed_in?
        'posts/branch/create_new_post/signed_in'
      else
        'posts/branch/create_new_post/not_signed_in'
      end
  end
 
  def all_categories_button_partial_path
    if params[:category].blank?
      'posts/branch/categories/all_selected'
    else
      'posts/branch/categories/all_not_selected'
    end
  end

  def no_posts_partial_path
    @posts.empty? ? 'posts/branch/no_posts' : 'shared/empty_partial'
  end

  def post_format_partial_path
    current_page?(root_path) ? 'posts/post/home_page' : 'posts/post/branch_page'
  end
  def category_field_partial_path
    if params[:category].present?
      'posts/branch/search_form/category_field'
    else
      'shared/empty_partial'
    end
  end
  def update_pagination_partial_path
    if @posts.next_page
      'posts/posts_pagination_page/update_pagination'
    else
      'posts/posts_pagination_page/remove_pagination'
    end
  end
end

app/views/layouts/navigation/_collapsible_elements.html.haml
/ Collect the nav links, forms, and other content for toggling
#navbar-collapsible-content.collapse.navbar-collapse.navbar-right
  %ul.nav.navbar-nav
    =render collapsible_links_partial_path

app/views/layouts/navigation/_header.html.haml
%ul.nav.navbar-nav.navbar-header
  %li= link_to "Home",   root_path

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.haml
%li= link_to 'Login', login_path
%li= link_to 'Signup', signup_path

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.haml
%li.dropdown.pc-menu
  %a#user-settings.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    %span#user-name= current_user.name
    %span.caret
  %ul.dropdown-menu{:role => "menu"}
    %li= link_to 'Edit Profile', edit_user_registration_path
    %li= link_to 'Log out', destroy_user_session_path, method: :delete
%li.mobile-menu
  = link_to 'Edit Profile', edit_user_registration_path
%li.mobile-menu
  = link_to 'Log out', destroy_user_session_path, method: :delete

app/views/posts/_branch.html.haml
#branch-main-content.container
  .row
    %h1.page-title
      = page_title
    = render 'posts/branch/create_new_post', branch: branch
  .row
    = render 'posts/branch/search_form',
              branch: branch,            
              search_placeholder: search_placeholder
  .row
    = render 'posts/branch/categories', branch: branch
  .row
    #feed.col-sm-12
      = render @posts
      = render no_posts_partial_path
  .infinite-scroll
    = will_paginate @posts

app/views/posts/_modal.html.haml
.modal.myModal{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content
      .modal-header
        %span.posted-by
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        .loaded-data
          %h3
          %p
          .interested
            %a{:href => ""} I'm interested

app/views/posts/_post.html.haml
= render post_format_partial_path, post: post

app/views/posts/_posts_pagination_page.js.erb
$('#feed').append('<%= j render @posts %>');
<%= render update_pagination_partial_path %>

app/views/posts/branch/_categories.html.haml
- branch_path_name = "#{params[:action]}_posts_path"
.col-sm-12
  %ul.categories-list
    = render all_categories_button_partial_path, branch_path_name: branch_path_name         
    - @categories.each do |category|
      %li.category-item
        = link_to category.name, 
                  send(branch_path_name, 
                  category: category.name), 
                  :class => ("selected-item" if params[:category] == category.name)

app/views/posts/branch/_create_new_post.html.haml
.col-sm-12
  .col-sm-8.col-sm-offset-2
    = render create_new_post_partial_path, branch: branch

app/views/posts/branch/_no_posts.html.haml
.text-center Currently there are no published posts

app/views/posts/branch/_search_form.html.haml
.col-sm-12
  = form_tag(send("#{branch}_posts_path"),
    :method => "get",
    id: "search-form") do
    %i.fa.fa-search{"aria-hidden" => "true"}
    = text_field_tag  :search,
      params[:search],
      placeholder: search_placeholder,
      class: "form-control"            
    = render category_field_partial_path

app/views/posts/branch/categories/_all_not_selected.html.haml
%li.category-item
  = link_to "All", send(branch_path_name)

app/views/posts/branch/categories/_all_selected.html.haml
%li.category-item
  = link_to "All", send(branch_path_name), :class => "selected-item" 

app/views/posts/branch/create_new_post/_not_signed_in.html.haml
.text-center.login-branch
  To create a new post you have to
  \#{link_to 'Login',  login_path,  class: 'login-button login-button-branch'}

app/views/posts/branch/create_new_post/_signed_in.html.haml
.new-post-button-parent
  %span Cannot find anyone? Try to:
  = link_to "Create a new post",   
    new_post_path(branch: branch), 
    :class => "new-post-button"    

app/views/posts/branch/search_form/_category_field.html.haml
= hidden_field_tag :category, params[:category]

app/views/posts/hobby.html.haml
= render 'posts/modal'
= render partial: 'posts/branch',
    locals: { branch: 'hobby',
    page_title: 'Find a person with the same hobby',
    search_placeholder: 'E.g. guitar playing, programming, cooking' } 

app/views/posts/post/_branch_page.html.haml
.single-post-list{:id => post_path(post.id) }
  =truncate(post.title, :length => 60)
  .post-content
    .posted-by
      Posted by #{post.user.name}
    %h3
      = post.title
    %p
      = post.content
    = link_to "I'm interested", post_path(post.id), class: 'interested'

app/views/posts/post/_home_page.html.haml
.col-sm-3.single-post-card{:id => post_path(post.id) } 
  .card
    .card-block
      %h4.post-text
        = truncate(post.title, :length => 60)
      .post-content
        .posted-by
          = "Posted by #{post.user.name}"
        %h3= post.title
        %p= post.content
        = link_to "I'm interested", post_path(post.id), class: 'interested'

app/views/posts/posts_pagination_page/_remove_pagination.js.erb
$(window).off('scroll');
$('.pagination').remove();

app/views/posts/posts_pagination_page/_update_pagination.js.erb
$('.pagination').replaceWith('<%= j will_paginate @posts %>');

app/views/posts/show.html.haml
#single-post-content.container
  .row
    .col-sm-6.col-sm-offset-3
      .posted-by
        Posted by
        =@post.user.name
      %h3=@post.title
      %p= @post.content

app/views/posts/study.html.haml
= render 'posts/modal'
= render partial: 'posts/branch',
    locals: { branch: 'study',
    page_title: 'Find a person who studies the same field as you',
    search_placeholder: 'E.g. nutrition, calculus, astrophysics' }

app/views/posts/team.html.haml
= render 'posts/modal'
= render partial: 'posts/branch', 
    locals: { branch: 'team',
    page_title: 'Find a person with similar interests as yours to your team',
    search_placeholder: 'E.g. musician for a band, developer for a project' }